<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.1.1 (Python 3.12.0 on win32)" generated="20231014 12:01:57.774" rpa="false" schemaversion="4">
<suite id="s1" name="cartDemo" source="C:\Users\Mohan\PycharmProjects\pythonProject\TestCode\AutomationDemo\cartDemo.robot">
<kw name="Open my browser" type="SETUP">
<msg timestamp="20231014 12:01:58.219" level="FAIL">No keyword with name 'Open my browser' found. Did you mean:
    SeleniumLibrary.Open Browser</msg>
<status status="FAIL" starttime="20231014 12:01:58.219" endtime="20231014 12:01:58.219"/>
</kw>
<test id="s1-t1" name="LoginTestwithExcel using" line="13">
<status status="FAIL" starttime="20231014 12:01:58.219" endtime="20231014 12:01:58.219">Parent suite setup failed:
No keyword with name 'Open my browser' found. Did you mean:
    SeleniumLibrary.Open Browser</status>
</test>
<kw name="Close All Browsers" library="SeleniumLibrary" type="TEARDOWN">
<doc>Closes all open browsers and resets the browser cache.</doc>
<status status="PASS" starttime="20231014 12:01:58.219" endtime="20231014 12:01:58.219"/>
</kw>
<status status="FAIL" starttime="20231014 12:01:57.774" endtime="20231014 12:01:58.219">Suite setup failed:
No keyword with name 'Open my browser' found. Did you mean:
    SeleniumLibrary.Open Browser</status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="cartDemo">cartDemo</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20231014 12:01:58.188" level="ERROR">Error in file 'C:\Users\Mohan\PycharmProjects\pythonProject\TestCode\AutomationDemo\cartDemo.robot' on line 3: Resource file '..\TestCode\AutomationDemo\keyword.robot' does not exist.</msg>
<msg timestamp="20231014 12:01:58.204" level="ERROR">[ DataDriver ] Error in robot file:
  File "C:\Users\Mohan\PycharmProjects\pythonProject\TestCode\AutomationDemo\cartDemo.robot", line 0</msg>
<msg timestamp="20231014 12:01:58.219" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: FileNotFoundError: File attribute was empty. Tried to find C:\Users\Mohan\PycharmProjects\pythonProject\TestCode\AutomationDemo\cartDemo.csv but file does not exist. If no file validation is required, set file_search_strategy=None.</msg>
</errors>
</robot>
